title: "Mikhael Hayes"
description: "A website about Mikhael's work in linguistics"
url: "https://mikhael2.github.io"
baseurl: ""
remote_theme: "just-the-docs/just-the-docs"
color_scheme: "dark"

# Preserve custom navigation order defined in _data/navigation.yml
nav_sort: false

nav_external_links:
  - title: "Alphabetter"
    url: "https://github.com/mikhael2/alphabetter-mac"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap

markdown: kramdown

atom_feed:
  hide: true
