title: "Mikhael Hayes"
description: "A website about Mikhael's academic work"
url: "https://mikhael2.github.io"
baseurl: ""

theme: jekyll-theme-tactile

plugins:
  - jekyll-sitemap

markdown: kramdown
